get http://localhost:3000/subscribers

###
get http://localhost:3000/subscribers/15

###

post http://localhost:3000/subscribers
Content-Type: application/json

{
    "name":"person2",
    "subscribedToChannel": "Web Dev"
}