get http://localhost:3000/subscribers

###
get http://localhost:3000/subscribers/60aa5a01efd9f52988a3ac07

###

post http://localhost:3000/subscribers
Content-Type: application/json

{
    "name":"person2",
    "subscribedToChannel": "Web Dev"
}

###
DELETE http://localhost:3000/subscribers/60aa5a01efd9f52988a3ac07

###

PATCH http://localhost:3000/subscribers/60aa65a4e337e02bb0177718
Content-Type: application/json

{
    "name":"ChangedName",
    "subscriberToChannel": "Still same"
}